apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: olea-platform-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: ""
    namespace: demo
    server: "https://kubernetes.default.svc"
  sources:
    - repoURL: "https://chris201222.github.io/helm-charts/"
      targetRevision: 1.0.0
      chart: olea-platform
      helm:
        valueFiles:
          - $values/qa/values.yaml
          - $values/qa/infra-values.yaml
    - repoURL: "git@github.com:chris201222/platform-config.git"
      targetRevision: HEAD
      ref: values
