# Default values for olea-platform.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The ingress configuration specific to AWS ALB Ingress and Traefik, not other Ingress Controller
ingress:
  enabled: false
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: "ALB_NAME" # ALB_NAME is the name of ALB (Required if ingress.enabled is true)
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/healthcheck-port: "9000"
    alb.ingress.kubernetes.io/healthcheck-path: /ping
    alb.ingress.kubernetes.io/subnets: "SUBNET1, SUBNET2, SUBNET3" # the subnets of ALB (Required if ingress.enabled is true)
    alb.ingress.kubernetes.io/certificate-arn: "CERTIFICATE_ARN" # the arn of certificate (Required if ingress.enabled is true)
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: DOMAIN_NAME
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              namespace: traefik # traefik is the namespace of traefik service
              name: traefik # traefik is the name of traefik service
              port:
                number: 80 # traefik service port

scheduler:
  enabled: false
  image: 855703743734.dkr.ecr.ap-southeast-1.amazonaws.com/olea/olea-simplescaler:v2
  scaleInPolicy:
    name: "olea-scheduler-daily-scale-in"
    schedule: "20 15 * * 1-5"
    namespace: dev
    replicas: 0
    resourceKind: deployment # supported resource kind:  Deployment, ARGO_ROLLOUT
  scaleOutPolicy:
    name: "olea-scheduler-daily-scale-out"
    schedule: "05 1 * * 1-5"
    namespace: dev
    replicas: 1
    resourceKind: deployment # supported resource kind:  Deployment, ARGO_ROLLOUT

ingressRoute:
  active:
    enabled: false
    name: olea-platform-ingress-route
    domainName: "qa.scvolea.com"
  preview:
    enabled: false # Set to true to enable preview environment
    name: olea-platform-ingress-route-preview
    domainName: "qa-preview.scvolea.com"
