{{- $top := . -}}
{{- range $deployment := .Values.deploymentList -}}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ $deployment.name }}
  labels:
    app: {{ $deployment.name }}
spec:
  replicas: {{ $deployment.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ $deployment.name }}
      environment: {{ $top.Values.commonConfig.environment }}
  template:
    metadata:
      labels:
        app: {{ $deployment.name }}
        environment: {{ $top.Values.commonConfig.environment }}
        {{- if $top.Values.commonConfig.useTimestampAsLabel }}
        timestamp: {{ now | unixEpoch | quote}}
        {{- end }}
    spec:
      serviceAccountName: {{ include "olea-platform.serviceAccountName" $top }}
      containers:
        - env:
        {{- if $deployment.extraEnvs }}
        {{- include "olea-platform.tplvalues.render" ( dict "value" $deployment.extraEnvs "context" $ ) | nindent 10 }}
        {{- end }}
        {{- if $deployment.configMapName }}
          envFrom:
            - configMapRef:
                name: {{ $deployment.configMapName }}
        {{- end }}
          name: {{ $deployment.name }}
          image: "{{ $top.Values.commonConfig.repository}}/{{$deployment.name}}:{{$deployment.imageTag}}"
          imagePullPolicy: {{ $top.Values.commonConfig.imagePullPolicy | default "IfNotPresent" }}
          resources:
            limits:
              cpu: {{ $deployment.cpuAllocated | default "1"}}
              memory: {{ $deployment.cpuAllocated  | default "1024Mi"}}
            requests:
              cpu: {{ $deployment.cpuAllocated | default "1" }}
              memory: {{ $deployment.cpuAllocated | default "1024Mi"}}
          ports:
            - name: http
              containerPort: {{ $deployment.containerPort | default 8080 }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            failureThreshold: 30
            successThreshold: 1
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 3
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 3
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 3
  strategy:
    blueGreen:
      activeService: {{ $deployment.name }}
      previewService: {{ $deployment.name }}-preview
      {{- toYaml $top.Values.strategy.Rollout.blueGreen | nindent 6 }}
---
{{- end}}