{{- $top := . -}}
{{- range $deployment := .Values.deploymentList -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ $deployment.name }}-preview"
  labels:
    app: "{{ $deployment.name }}-preview"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ $deployment.containerPort | default 8080 }}
      protocol: TCP
      name: http
  selector:
    app: {{ $deployment.name }}
---
{{- end}}
